name: NDK build

on:
  push:
    branches:
      - 'main'
      - 'dev/**'
      - 'feat/**'
    paths-ignore:
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Create ndkpath.txt
        run: |
          echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
          cat ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: build
        run: pwsh ./scripts/build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libyodel.so
          path: ./build/libyodel.so
          if-no-files-found: error
